In [ ]:
'''

Assignment 5: Diabetes Prediction
Dataset: PIMA Diabetes
Link: https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv
Task:
 Predict diabetes outcome.
 Replace 0 values in features like BMI, Glucose with median.
 StandardScaler for all features.
 Train logistic regression and interpret coefficients
'''

In [1]:
import pandas as pd

C:\Users\Saikat Maiti\Downloads\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
import numpy as np

In [8]:
z = df[df['Glucose']==0]
print(z)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
75             1        0             48             20        0  24.7   
182            1        0             74             20       23  27.7   
342            1        0             68             35        0  32.0   
349            5        0             80             32        0  41.0   
502            6        0             68             41        0  39.0   

     DiabetesPedigreeFunction  Age  Outcome  
75                      0.140   22        0  
182                     0.299   21        0  
342                     0.389   22        0  
349                     0.346   37        1  
502                     0.727   41        1  


In [10]:
df['Glucose'] = df['Glucose'].replace(0,df['Glucose'].median())

In [13]:
df[df['BloodPressure']==0]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
7             10      115              0              0        0  35.3   
15             7      100              0              0        0  30.0   
49             7      105              0              0        0   0.0   
60             2       84              0              0        0   0.0   
78             0      131              0              0        0  43.2   
81             2       74              0              0        0   0.0   
172            2       87              0             23        0  28.9   
193           11      135              0              0        0  52.3   
222            7      119              0              0        0  25.2   
261            3      141              0              0        0  30.0   
266            0      138              0              0        0  36.3   
269            2      146              0              0        0  27.5   
300            0      167              0              0        0  32.3   
332            1      180              0              0        0  43.3   
336            0      117              0              0        0  33.8   
347            3      116              0              0        0  23.5   
357           13      129              0             30        0  39.9   
426            0       94              0              0        0   0.0   
430            2       99              0              0        0  22.2   
435            0      141              0              0        0  42.4   
453            2      119              0              0        0  19.6   
468            8      120              0              0        0  30.0   
484            0      145              0              0        0  44.2   
494            3       80              0              0        0   0.0   
522            6      114              0              0        0   0.0   
533            6       91              0              0        0  29.8   
535            4      132              0              0        0  32.9   
589            0       73              0              0        0  21.1   
601            6       96              0              0        0  23.7   
604            4      183              0              0        0  28.4   
619            0      119              0              0        0  32.4   
643            4       90              0              0        0  28.0   
697            0       99              0              0        0  25.0   
703            2      129              0              0        0  38.5   
706           10      115              0              0        0   0.0   

     DiabetesPedigreeFunction  Age  Outcome  
7                       0.134   29        0  
15                      0.484   32        1  
49                      0.305   24        0  
60                      0.304   21        0  
78                      0.270   26        1  
81                      0.102   22        0  
172                     0.773   25        0  
193                     0.578   40        1  
222                     0.209   37        0  
261                     0.761   27        1  
266                     0.933   25        1  
269                     0.240   28        1  
300                     0.839   30        1  
332                     0.282   41        1  
336                     0.932   44        0  
347                     0.187   23        0  
357                     0.569   44        1  
426                     0.256   25        0  
430                     0.108   23        0  
435                     0.205   29        1  
453                     0.832   72        0  
468                     0.183   38        1  
484                     0.630   31        1  
494                     0.174   22        0  
522                     0.189   26        0  
533                     0.501   31        0  
535                     0.302   23        1  
589                     0.342   25        0  
601   

In [14]:
df['BloodPressure'] = df['BloodPressure'].replace(0,df['BloodPressure'].median())

In [15]:
df['SkinThickness'] = df['SkinThickness'].replace(0,df['SkinThickness'].median())

In [16]:
df['Insulin'] = df['Insulin'].replace(0,df['Insulin'].median())

In [17]:
df[df['BMI']==0]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
9              8      125             96             23     30.5  0.0   
49             7      105             72             23     30.5  0.0   
60             2       84             72             23     30.5  0.0   
81             2       74             72             23     30.5  0.0   
145            0      102             75             23     30.5  0.0   
371            0      118             64             23     89.0  0.0   
426            0       94             72             23     30.5  0.0   
494            3       80             72             23     30.5  0.0   
522            6      114             72             23     30.5  0.0   
684            5      136             82             23     30.5  0.0   
706           10      115             72             23     30.5  0.0   

     DiabetesPedigreeFunction  Age  Outcome  
9                       0.232   54        1  
49                      0.305   24        0  
60                      0.304   21        0  
81                      0.102   22        0  
145                     0.572   21        0  
371                     1.731   21        0  
426                     0.256   25        0  
494                     0.174   22        0  
522                     0.189   26        0  
684                     0.640   69        0  
706                     0.261   30        1

In [18]:
df['BMI'] = df['BMI'].replace(0,df['BMI'].median())

In [20]:
df[df['DiabetesPedigreeFunction']==0]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [21]:
df[df['Age']==0]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [22]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35     30.5  33.6   
1              1       85             66             29     30.5  26.6   
2              8      183             64             23     30.5  23.3   
3              1       89             66             23     94.0  28.1   
4              0      137             40             35    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48    180.0  32.9   
764            2      122             70             27     30.5  36.8   
765            5      121             72             23    112.0  26.2   
766            1      126             60             23     30.5  30.1   
767            1       93             70             31     30.5  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler()

In [28]:
scaler.fit(df.iloc[:,0:8])

StandardScaler()

In [29]:
df.iloc[:,0:8] = scaler.transform(df.iloc[:,0:8])

C:\Users\Saikat Maiti\AppData\Local\Temp\ipykernel_12940\293762646.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.63994726 -0.84488505  1.23388019 -0.84488505 -1.14185152  0.3429808
 -0.25095213  1.82781311 -0.54791859  1.23388019  0.04601433  1.82781311
  1.82781311 -0.84488505  0.3429808   0.93691372 -1.14185152  0.93691372
 -0.84488505 -0.84488505 -0.25095213  1.23388019  0.93691372  1.53084665
  2.12477957  1.82781311  0.93691372 -0.84488505  2.7187125   0.3429808
  0.3429808  -0.25095213 -0.25095213  0.63994726  1.82781311  0.04601433
  2.12477957  1.53084665 -0.54791859  0.04601433 -0.25095213  0.93691372
  0.93691372  1.53084665  0.93691372 -1.14185152 -0.84488505 -0.54791859
  0.93691372  0.93691372 -0.84488505 -0.84488505  0.3429808   1.23388019
  0.93691372 -0.84488505  0.93691372 -1.14185152 -1.14185152 -1.14185152
 -0.54791859  1.23388019  0.3429808  -0.54791859  0.93691372  0.3429808
 -1.14185

In [30]:
df

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.639947  0.866045      -0.031990       0.831114 -0.608201  0.167240   
1      -0.844885 -1.205066      -0.528319       0.180566 -0.608201 -0.851551   
2       1.233880  2.016662      -0.693761      -0.469981 -0.608201 -1.331838   
3      -0.844885 -1.073567      -0.528319      -0.469981 -0.006185 -0.633239   
4      -1.141852  0.504422      -2.679076       0.831114  0.695378  1.549885   
..           ...       ...            ...            ...       ...       ...   
763     1.827813 -0.679069       0.298896       2.240633  0.809145  0.065361   
764    -0.547919  0.011301      -0.197433      -0.036283 -0.608201  0.632973   
765     0.342981 -0.021574      -0.031990      -0.469981  0.164466 -0.909768   
766    -0.844885  0.142800      -1.024647      -0.469981 -0.608201 -0.342155   
767    -0.844885 -0.942068      -0.197433       0.397415 -0.608201 -0.298493   

     DiabetesPedigreeFunction       Age  Outcome  
0                    0.468492  1.425995        1  
1                   -0.365061 -0.190672        0  
2                    0.604397 -0.105584        1  
3                   -0.920763 -1.041549        0  
4                    5.484909 -0.020496        1  
..                        ...       ...      ...  
763                 -0.908682  2.532136        0  
764                 -0.398282 -0.531023        0  
765                 -0.685193 -0.275760        0  
766                 -0.371101  1.170732        1  
767                 -0.473785 -0.871374        0  

[768 rows x 9 columns]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x = df.iloc[:,0:8]

In [34]:
y = df['Outcome'].values

In [35]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
lr = LogisticRegression()

In [40]:
lr.fit(x_train,y_train)

LogisticRegression()

In [41]:
y_pred = lr.predict(x_test)

In [42]:
lr.intercept_

array([-0.89001774])

In [43]:
lr.coef_

array([[ 0.43393365,  1.11779558, -0.10065558,  0.06530675, -0.11974128,
         0.5685035 ,  0.25891383,  0.04981461]])

In [46]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [45]:
accuracy_score(y_test,y_pred)

0.7662337662337663

In [47]:
confusion_matrix(y_test,y_pred)

array([[85,  8],
       [28, 33]], dtype=int64)

In [48]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      0.91      0.83        93
           1       0.80      0.54      0.65        61

    accuracy                           0.77       154
   macro avg       0.78      0.73      0.74       154
weighted avg       0.77      0.77      0.75       154

